"""add transaction_id

Revision ID: 30904f91d507
Revises: 552cce5d76f2
Create Date: 2026-07-15 14:21:09.452099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30904f91d507'
down_revision: Union[str, Sequence[str], None] = '552cce5d76f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('paid_amount', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('paid_currency', sa.String(length=10), nullable=False))
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('payments', 'paid_currency')
    op.drop_column('payments', 'paid_amount')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
